### ISSUE TITLE
New features and Improvements

### ISSUE THREAD

**Issue by SayantanD99** [SayantanD99/Frequency-Tester#1]
> Kindly check into these following matters and help me if you can in improving this piece of code.

Issues - >

- [x] If the program could segregate between '.' and other words.
- [x]  It would be better if we didn't have to give spaces before and after '.' in the input for getting accurate results.

- [ ] To check for the frequency of multiple words in the entered paragraph.

> Feedbacks are highly appreciated. If you can help me improve the code or do find any bugs, then do let me know.

> Thanks if you are looking into it. Any sort of help will be appreciated.

**Comment by scaunois** [comment]
Hi, I have created a pull request for you, that successfully correct your use case with the 'dot'.
